filter:
    paths:
        - src/VoltDB/*
    excluded_paths:
        - tests/*
tools:
    php_code_sniffer:
        config:
            standard: "PSR2"
    php_cs_fixer:
        config: { level: psr2 }
checks:
    php:
        code_rating: true
        duplication: true
