language: php

php:
  - 5.4
  - 5.5
  - 5.6

before_script:
  - sudo apt-get update -qq
  - sudo apt-get install gcc
  - sudo apt-get install libboost-all-dev
  - git clone -b noexceptions https://github.com/VoltDB/voltdb-client-cpp.git
  - cd voltdb-client-cpp
  - make
  - cd ..
  - git clone -b native https://github.com/VoltDB/voltdb-client-php.git
  - cd voltdb-client-php
  - phpize
  - ./configure --with-voltdb=../voltdb-client-cpp
  - make
  - echo "extension=voltdb.so" > voltdb.ini && phpenv config-add voltdb.ini
  - composer self-update
  - composer install

script: phpunit

notifications:
  emails:
    - yuuki.takezawa@comnect.jp.net
